# Generated by Django 5.2.7 on 2026-04-25 18:37

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Eleve',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matricule', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('nom', models.CharField(max_length=100)),
                ('prenoms', models.CharField(max_length=100)),
                ('sexe', models.CharField(choices=[('M', 'Masculin'), ('F', 'Féminin')], max_length=10)),
                ('date_naissance', models.DateField(blank=True, null=True)),
                ('lieu_naissance', models.CharField(blank=True, max_length=100, null=True)),
                ('nationalite', models.CharField(default='Béninoise', max_length=50)),
                ('profile_eleve', models.ImageField(blank=True, null=True, upload_to='profile_images/')),
                ('annee_academique', models.CharField(help_text='Ex: 2023-2024', max_length=50)),
                ('classe', models.CharField(choices=[('6ème', '6ème'), ('5ème', '5ème'), ('4ème', '4ème'), ('3ème', '3ème'), ('2nde', 'Seconde'), ('1ère', 'Première'), ('Tle', 'Terminale')], max_length=50)),
                ('serie', models.CharField(blank=True, choices=[('Général', 'Général (Collège)'), ('A1', 'Série A1'), ('A2', 'Série A2'), ('B', 'Série B'), ('C', 'Série C'), ('D', 'Série D')], default='Général', max_length=10)),
                ('langue_specialite', models.CharField(blank=True, choices=[('Espagnol', 'Espagnol'), ('Allemand', 'Allemand')], help_text='À remplir uniquement pour les élèves de 4ème et 3ème.', max_length=20, null=True, verbose_name='Langue de Spécialité (Collège)')),
                ('lv1', models.CharField(choices=[('Anglais', 'Anglais'), ('Espagnol', 'Espagnol'), ('Allemand', 'Allemand')], default='Anglais', max_length=20, verbose_name='Langue Vivante 1 (Lycée)')),
                ('lv2', models.CharField(blank=True, choices=[('Anglais', 'Anglais'), ('Espagnol', 'Espagnol'), ('Allemand', 'Allemand')], max_length=20, null=True, verbose_name='Langue Vivante 2 (Lycée)')),
                ('telephone_parent', models.CharField(blank=True, max_length=15, null=True)),
                ('email_parent', models.EmailField(blank=True, max_length=254, null=True)),
                ('date_enregistrement', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Élève',
                'verbose_name_plural': 'Élèves',
                'ordering': ['nom', 'prenoms'],
            },
        ),
        migrations.CreateModel(
            name='Enseignant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=150)),
                ('prenoms', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=255)),
                ('matiere', models.CharField(blank=True, max_length=255)),
                ('classes', models.CharField(max_length=200)),
                ('series', models.CharField(blank=True, max_length=100, null=True)),
                ('annee_academique', models.CharField(max_length=20)),
                ('est_approuve', models.BooleanField(default=False)),
                ('is_verified', models.BooleanField(default=False)),
                ('otp_code', models.CharField(blank=True, max_length=6, null=True)),
                ('otp_timestamp', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Login',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('school_name', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('numero', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=100, null=True)),
                ('profile_image', models.ImageField(blank=True, null=True, upload_to='profile_images/')),
                ('coin_droit', models.ImageField(blank=True, null=True, upload_to='cartes/recto/')),
                ('fond_verso', models.ImageField(blank=True, null=True, upload_to='cartes/verso/')),
                ('latitude', models.DecimalField(decimal_places=16, default=6.505650347028947, max_digits=22)),
                ('longitude', models.DecimalField(decimal_places=16, default=2.5984622632404064, max_digits=22)),
            ],
        ),
        migrations.CreateModel(
            name='Horaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('classe', models.CharField(max_length=20)),
                ('jour', models.CharField(max_length=10)),
                ('heure_debut', models.TimeField()),
                ('heure_fin', models.TimeField()),
                ('matiere', models.CharField(max_length=50)),
                ('annee_academique', models.CharField(max_length=20)),
                ('enseignant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.enseignant')),
            ],
        ),
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matiere', models.CharField(max_length=100)),
                ('trimestre', models.IntegerField()),
                ('valeur', models.FloatField()),
                ('type_note', models.CharField(max_length=20)),
                ('moyenne_interrogations', models.FloatField(blank=True, null=True)),
                ('moyenne_devoirs', models.FloatField(blank=True, null=True)),
                ('moyenne_generale', models.FloatField(blank=True, null=True)),
                ('moyenne_trimestrielle', models.FloatField(blank=True, default=0.0, null=True)),
                ('rang', models.IntegerField(blank=True, null=True)),
                ('date_ajout', models.DateTimeField(default=django.utils.timezone.now)),
                ('annee_academique', models.CharField(blank=True, max_length=10, null=True)),
                ('eleve', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.eleve')),
            ],
        ),
        migrations.CreateModel(
            name='Presence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('classe', models.CharField(max_length=100)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('etat', models.CharField(choices=[('present', 'Présent'), ('absent', 'Absent')], max_length=20)),
                ('motif', models.CharField(blank=True, max_length=255, null=True)),
                ('duree', models.FloatField(blank=True, null=True)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('eleve', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.eleve')),
                ('enseignant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.enseignant')),
                ('horaire', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='myapp.horaire')),
            ],
        ),
        migrations.CreateModel(
            name='ProfesseurPrincipal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('classe', models.CharField(max_length=50)),
                ('serie', models.CharField(blank=True, max_length=50, null=True)),
                ('annee_academique', models.CharField(max_length=20)),
                ('enseignant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.enseignant')),
            ],
            options={
                'unique_together': {('classe', 'serie', 'annee_academique')},
            },
        ),
    ]
