# Generated by Django 5.2.7 on 2026-04-30 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eleve',
            name='serie',
            field=models.CharField(blank=True, choices=[('Général', 'Général (Collège)'), ('A1', 'Série A1'), ('A2', 'Série A2'), ('B', 'Série B'), ('C', 'Série C'), ('D', 'Série D')], max_length=10, null=True),
        ),
    ]
