# Generated by Django 5.2.7 on 2026-04-30 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_alter_eleve_serie'),
    ]

    operations = [
        migrations.AddField(
            model_name='enseignant',
            name='signature',
            field=models.ImageField(blank=True, null=True, upload_to='signatures/'),
        ),
    ]
